# Generated by Django 4.0.6 on 2023-04-08 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid Kenyan phone number starting with "+254"', regex='^\\+254\\d{9}$')]),
        ),
    ]
